azure:
  namespace: "![a8D+hR6Rlo84NnUDptgiF8sRdW9kETcP]"
  accesskey: "![HJPkWfEC3/G7F3S9R6I55vQGdWJ0owGtsrQhZwl9cBo=]"
  sas: "![8MJRST1wSZFIuefWHEMJqqQy+mcmT9rJIV4VcFXH/xVIBn0m6VefyIJ1hP9RAJXw]"
db:
  url: "![wsGoMaJ6HRYmGR5lsFMsZGzp0k/hzPAZf9LRA2+wNaVx5cxuTXYsZwq6rRljHQ/wzDCybDc8Mb15pobU2Uta3w==]"
  driver: "![/YDCZGJz0PxGpsqXjj9Xm4ND5zLT8HFr]"
  user: "![hDoP7wxnPOR9YIFKna48TA==]"
  password: "![ve9tf5nh+qNbF/Ytamh6gGDkLqUdG2O13bIsZBEI7yq5k2pPoBiZeA==]"